<?php

namespace ReclamationBundle\Repository;

/**
 * RaisonsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RaisonsRepository extends \Doctrine\ORM\EntityRepository
{
}
