assoc_produit:
    resource: "@ProduitBundle/Resources/config/routing/produit.yml"
    prefix: /produit

assoc_categorie:
    resource: "@ProduitBundle/Resources/config/routing/categorie.yml"
    prefix: /categorie