commentaire_index:
    path:     /
    defaults: { _controller: "ForumBundle:CommentaireF:index" }
    methods:  GET

commentaire_show:
    path:     /{id}/show
    defaults: { _controller: "ForumBundle:CommentaireF:show" }
    methods:  GET

commentaire_new:
    path:     /new
    defaults: { _controller: "ForumBundle:CommentaireF:new" }
    methods:  [GET, POST]

commentaire_edit:
    path:     /{id}/edit
    defaults: { _controller: "ForumBundle:CommentaireF:edit" }
    methods:  [GET, POST]

commentaire_delete:
    path:     /{id}/delete
    defaults: { _controller: "ForumBundle:CommentaireF:delete" }
    methods:  DELETE
