event_index:
    path:     /
    defaults: { _controller: "AssocBundle:Event:index" }

event_search:
    path:     /
    defaults: { _controller: "AssocBundle:Event:search" }

event_show:
    path:     /{id}/show
    defaults: { _controller: "AssocBundle:Event:show" }
event_list:
    path:     /list
    defaults: { _controller: "AssocBundle:Event:listEvent" }

event_interested:
    path:     /{id}/interest
    defaults: { _controller: "AssocBundle:Event:interested" }

event_new:
    path:     /new
    defaults: { _controller: "AssocBundle:Event:new" }
    methods:  [GET, POST]

event_edit:
    path:     /{id}/edit
    defaults: { _controller: "AssocBundle:Event:edit" }
    methods:  [GET, POST]

event_delete:
    path:     /{id}/delete
    defaults: { _controller: "AssocBundle:Event:delete" }
    methods:  DELETE
