forum_index:
    path:     /
    defaults: { _controller: "AssocBundle:Forum:index" }
    methods:  GET

forum_show:
    path:     /{id}/show
    defaults: { _controller: "AssocBundle:Forum:show" }
    methods:  GET

forum_new:
    path:     /new
    defaults: { _controller: "AssocBundle:Forum:new" }
    methods:  [GET, POST]

forum_edit:
    path:     /{id}/edit
    defaults: { _controller: "AssocBundle:Forum:edit" }
    methods:  [GET, POST]

forum_delete:
    path:     /{id}/delete
    defaults: { _controller: "AssocBundle:Forum:delete" }
    methods:  DELETE
