user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

forum:
    resource: "@ForumBundle/Resources/config/routing.yml"
    prefix:   /

collecte:
    resource: "@CollecteBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

reclamation:
    resource: "@ReclamationBundle/Resources/config/routing.yml"
    prefix:   /

publication:
    resource: "@PublicationBundle/Resources/config/routing.yml"
    prefix:   /

produit:
    resource: "@ProduitBundle/Resources/config/routing.yml"
    prefix:   /


saviors:
    resource: "@SaviorsBundle/Resources/config/routing.yml"
    prefix:   /hello

assoc:
    resource: "@AssocBundle/Resources/config/routing.yml"
    prefix:   /
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
