<?php

namespace CollecteBundle\Repository;

/**
 * CategorieCollectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieCollectRepository extends \Doctrine\ORM\EntityRepository
{
}
