<?php

namespace CollecteBundle\Repository;

/**
 * CollectPendingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollectPendingRepository extends \Doctrine\ORM\EntityRepository
{
    public function showByCat($typeCategorie) {
        $em = $this->getEntityManager();
        $dql = $em->createQuery("SELECT c 
        FROM CollecteBundle\Entity\CollectPending c
        WHERE c.categorieCollect = :typeCategorie")->setParameter('typeCategorie', $typeCategorie);
        $result = $dql->getResult();
        return $result;
    }
}
