<?php

namespace ProduitBundle\Repository;

/**
 * ProduitPendingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitPendingRepository extends \Doctrine\ORM\EntityRepository
{
    public function CategoryFilter( $category){

        $dql='SELECT p   FROM ProduitBundle:ProduitPending p  join p.categorie c
         WHERE   c.nom like :categorie';
        $em = $this->getEntityManager();
        $query = $em->createQuery($dql)->setParameter('categorie', '%'.$category.'%' );
        return  $query->getResult();

    }


    public function NameFilter($str ){

        $dql='SELECT p   FROM ProduitBundle:ProduitPending p  
         WHERE   p.nom LIKE :str  ';
        $em = $this->getEntityManager();
        $query = $em->createQuery($dql)->setParameter('str', '%'.$str.'%');
        return  $query->getResult();

    }


    public function DeepFilter($str,$category){

        $dql='SELECT p   FROM ProduitBundle:ProduitPending p  join p.categorie c
         WHERE   p.nom LIKE :str and c.nom like :categorie';
        $em = $this->getEntityManager();
        $query = $em->createQuery($dql)->setParameter('str', '%'.$str.'%')->setParameter('categorie', '%'.$category.'%' );
        return  $query->getResult();

    }

}
