<?php

namespace ProduitBundle\Repository;

/**
 * ProduitcommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitcommentRepository extends \Doctrine\ORM\EntityRepository
{
}
