<?php

namespace AssocBundle\Repository;

/**
 * comment_eventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class comment_eventRepository extends \Doctrine\ORM\EntityRepository
{
}
