<?php

namespace AssocBundle\Repository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
    public  function findByMot($mot) {
       $query = $this->createQueryBuilder('e')
            ->where('e.name LIKE :mot')
            ->setParameter('mot', '%'.$mot.'%')
           ->getQuery();

       return $query->getResult();
    }
}
