<?php

namespace PublicationBundle\Repository;

/**
 * AimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AimeRepository extends \Doctrine\ORM\EntityRepository
{
}
