<?php

namespace PublicationBundle\Repository;

/**
 * PublicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicationRepository extends \Doctrine\ORM\EntityRepository
{
  public function search($keywords) {
    $query = $this->createQueryBuilder('s');
    if($keywords != '') {
      $query->andWhere("s.titre LIKE '%$keywords%' OR s.description LIKE '%$keywords%'");
    }
    return $query->getQuery()->getResult();
  }
}
