<?php

namespace ForumBundle\Repository;

/**
 * forumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForumRepository extends \Doctrine\ORM\EntityRepository
{
    public function findQuestionByCat($id)
    {
        $em = $this->getEntityManager();
        $dql=$em->createQuery("SELECT f
        FROM ForumBundle\Entity\Forum f
        WHERE f.categorieForum =:id")->setParameter('id', $id);
        $result=$dql->getResult();
        return  $result;
    }
}
