commentaire_index:
    path:     /
    defaults: { _controller: "PublicationBundle:CommentaireP:index" }
    methods:  GET

commentaire_show:
    path:     /{id}/show
    defaults: { _controller: "PublicationBundle:CommentaireP:show" }
    methods:  GET

commentaire_new:
    path:     /new-comment/{id}
    defaults: { _controller: "PublicationBundle:CommentaireP:new" }
    methods:  [GET, POST]

commentaire_edit:
    path:     /{id}/edit
    defaults: { _controller: "PublicationBundle:CommentaireP:edit" }
    methods:  [GET, POST]

commentaire_delete:
    path:     /{id}/delete
    defaults: { _controller: "PublicationBundle:CommentaireP:delete" }
    methods:  DELETE
